// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsTHD_CeIkz4Z-EVAUKlRrb3Zns_KOfk',
    appId: '1:260731702107:web:2d1fc064f31f8ea366e87e',
    messagingSenderId: '260731702107',
    projectId: 'market-bi-598da',
    authDomain: 'market-bi-598da.firebaseapp.com',
    storageBucket: 'market-bi-598da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpMKYNvhNuOjkdFyuZKoh9UQK2KAb7XT0',
    appId: '1:260731702107:android:cca679ac0b40cf3e66e87e',
    messagingSenderId: '260731702107',
    projectId: 'market-bi-598da',
    storageBucket: 'market-bi-598da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFJv8Yn340nuWsEgbLVFc22E0bpW8AFmo',
    appId: '1:260731702107:ios:9418f0e5de4bbf0d66e87e',
    messagingSenderId: '260731702107',
    projectId: 'market-bi-598da',
    storageBucket: 'market-bi-598da.appspot.com',
    iosClientId:
        '260731702107-493gdp3bsbgv37rq8eerfhsnnmfqt2h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketBi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFJv8Yn340nuWsEgbLVFc22E0bpW8AFmo',
    appId: '1:260731702107:ios:9418f0e5de4bbf0d66e87e',
    messagingSenderId: '260731702107',
    projectId: 'market-bi-598da',
    storageBucket: 'market-bi-598da.appspot.com',
    iosClientId:
        '260731702107-493gdp3bsbgv37rq8eerfhsnnmfqt2h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketBi',
  );
}
